// Auto-generated by contracts/scripts/generate-relayer-config.js
// Do not edit manually - run 'make sync' in contracts/ to regenerate

import type { ChainConfig } from './types.js'

// Chain configurations with deployment addresses
export const CHAIN_CONFIGS: Record<string, ChainConfig> = {
  arbitrumSepolia: {
    chainId: 421614,
    name: 'Arbitrum Sepolia',
    rpcUrl: process.env.ARBITRUM_SEPOLIA_RPC || 'https://sepolia-rollup.arbitrum.io/rpc',
    policyManagerAddress: '0x9c75bf193445FbC5AA860DcbbF2E9ad84124bD63' as `0x${string}`,
    startBlock: 243344057,
    pollIntervalMs: 15000,
    batchSize: 9000,
    confirmations: 2,
    enabled: true,
    minGasFees: {
      maxPriorityFeePerGas: 1000000000n,
      maxFeePerGas: 50000000000n,
    },
  }
} as const

// Deployment metadata
export const DEPLOYMENTS = {
  "5042002": {
    "chainId": 5042002,
    "chainName": "arcTestnet",
    "deployedAt": "2026-02-12T02:51:00Z",
    "deployer": "0x7E31DF5336c97BE4Fe34B4D05CbBaae354d383F9",
    "deployBlock": 26573469,
    "contracts": {
      "arcPolicyManager": "0xe3463a10Cb69D9705A38cECac3cBC58AD76f5De1"
    },
    "addresses": {
      "usdc": "0x3600000000000000000000000000000000000000",
      "feeRecipient": "0x2B8b9182c1c3A9bEf4a60951D9B7F49420D12B9B"
    }
  }
} as const

// Get enabled chains
export function getEnabledChainConfigs(): ChainConfig[] {
  return Object.values(CHAIN_CONFIGS).filter(c => c.enabled)
}

// Get chain config by ID
export function getChainConfigById(chainId: number): ChainConfig | undefined {
  return Object.values(CHAIN_CONFIGS).find(c => c.chainId === chainId)
}
