// Auto-generated by scripts/generate-contracts-ts.js
// Do not edit manually - run 'make sync' to regenerate

import ArbPolicyManagerAbi from './abis/ArbPolicyManager.json';
// import PolicyManagerAbi from './abis/PolicyManager.json';

export { ArbPolicyManagerAbi };

// Chain configurations
export const CHAINS = {
  "arbitrumSepolia": {
    "id": 421614,
    "name": "Arbitrum Sepolia",
    "rpcUrl": "https://sepolia-rollup.arbitrum.io/rpc",
    "usdc": "0x75faf114eafb1BDbe2F0316DF893fd58CE46AA4d",
    "blockExplorer": "https://sepolia.arbiscan.io"
  }
} as const;

// Deployment addresses by chain ID
export const DEPLOYMENTS: Record<number, Deployment> = {
  "421614": {
    "chainId": 421614,
    "chainName": "arbitrum-sepolia",
    "deployedAt": "2026-02-17T16:37:12Z",
    "deployer": "0x690C65EB2e2dd321ACe41a9865Aea3fAa98be2A5",
    "deployBlock": 243344057,
    "contracts": {
      "arbPolicyManager": "0x9c75bf193445FbC5AA860DcbbF2E9ad84124bD63"
    },
    "addresses": {
      "usdc": "0x75faf114eafb1BDbe2F0316DF893fd58CE46AA4d",
      "feeRecipient": "0x690C65EB2e2dd321ACe41a9865Aea3fAa98be2A5"
    }
  }
};

// Types
export interface Deployment {
  chainId: number;
  chainName: string;
  deployedAt: string;
  deployer: string;
  deployBlock?: number;
  contracts: {
    arbPolicyManager?: string;
    policyManager?: string;
  };
  addresses: {
    usdc: string;
    feeRecipient: string;
  };
}

// Helpers
export function getContractAddress(
  chainId: number,
  contract: 'arbPolicyManager' | 'policyManager'
): `0x${string}` {
  const deployment = DEPLOYMENTS[chainId];
  if (!deployment) {
    throw new Error(`No deployment found for chain ${chainId}`);
  }
  const address = deployment.contracts[contract];
  if (!address) {
    throw new Error(`Contract ${contract} not deployed on chain ${chainId}`);
  }
  return address as `0x${string}`;
}

export function getChainConfig(chainId: number) {
  const chain = Object.values(CHAINS).find(c => c.id === chainId);
  if (!chain) {
    throw new Error(`Unknown chain ${chainId}`);
  }
  return chain;
}
