// Auto-generated by scripts/generate-contracts-ts.js
// Do not edit manually - run 'make sync' to regenerate

import ArbPolicyManagerAbi from './abis/ArbPolicyManager.json';
// import PolicyManagerAbi from './abis/PolicyManager.json';

export { ArbPolicyManagerAbi };

// Chain configurations
export const CHAINS = {
  "arbitrumSepolia": {
    "id": 421614,
    "name": "Arbitrum Sepolia",
    "rpcUrl": "https://sepolia-rollup.arbitrum.io/rpc",
    "usdc": "0x75faf114eafb1BDbe2F0316DF893fd58CE46AA4d",
    "blockExplorer": "https://sepolia.arbiscan.io"
  }
} as const;

// Deployment addresses by chain ID
export const DEPLOYMENTS: Record<number, Deployment> = {
  "5042002": {
    "chainId": 5042002,
    "chainName": "arc-testnet",
    "deployedAt": "2026-02-12T02:51:00Z",
    "deployer": "0x7E31DF5336c97BE4Fe34B4D05CbBaae354d383F9",
    "deployBlock": 26573469,
    "contracts": {
      "arbPolicyManager": "0xe3463a10Cb69D9705A38cECac3cBC58AD76f5De1"
    },
    "addresses": {
      "usdc": "0x3600000000000000000000000000000000000000",
      "feeRecipient": "0x2B8b9182c1c3A9bEf4a60951D9B7F49420D12B9B"
    }
  },
  "43113": {
    "chainId": 43113,
    "chainName": "avalanche-fuji",
    "deployedAt": "2026-05-17T09:49:19Z",
    "deployer": "0x429cB52eC6a7Fc28bC88431909Ae469977F6daCF",
    "deployBlock": 55461417,
    "contracts": {
      "arbPolicyManager": "0xc4Eb29627B1b0FF88410Fad383F14492F4851FEe"
    },
    "addresses": {
      "usdc": "0x5425890298aed601595a70AB815c96711a31Bc65",
      "feeRecipient": "0x429cB52eC6a7Fc28bC88431909Ae469977F6daCF"
    }
  },
  "421614": {
    "chainId": 421614,
    "chainName": "arbitrum-sepolia",
    "deployedAt": "2026-02-17T16:37:12Z",
    "deployer": "0x690C65EB2e2dd321ACe41a9865Aea3fAa98be2A5",
    "deployBlock": 243344057,
    "contracts": {
      "arbPolicyManager": "0x9c75bf193445FbC5AA860DcbbF2E9ad84124bD63"
    },
    "addresses": {
      "usdc": "0x75faf114eafb1BDbe2F0316DF893fd58CE46AA4d",
      "feeRecipient": "0x690C65EB2e2dd321ACe41a9865Aea3fAa98be2A5"
    }
  }
};

// Types
export interface Deployment {
  chainId: number;
  chainName: string;
  deployedAt: string;
  deployer: string;
  deployBlock?: number;
  contracts: {
    arbPolicyManager?: string;
    policyManager?: string;
  };
  addresses: {
    usdc: string;
    feeRecipient: string;
  };
}

// Helpers
export function getContractAddress(
  chainId: number,
  contract: 'arbPolicyManager' | 'policyManager'
): `0x${string}` {
  const deployment = DEPLOYMENTS[chainId];
  if (!deployment) {
    throw new Error(`No deployment found for chain ${chainId}`);
  }
  const address = deployment.contracts[contract];
  if (!address) {
    throw new Error(`Contract ${contract} not deployed on chain ${chainId}`);
  }
  return address as `0x${string}`;
}

export function getChainConfig(chainId: number) {
  const chain = Object.values(CHAINS).find(c => c.id === chainId);
  if (!chain) {
    throw new Error(`Unknown chain ${chainId}`);
  }
  return chain;
}
